export const GET_LIST_LIVE_STREAM = 'GET_LIST_LIVE_STREAM'
export const GET_LIST_LIVE_STREAM_SUCCESS = 'GET_LIST_LIVE_STREAM_SUCCESS'

export const GET_LINK_LIVE_STREAM_CLIENT = 'GET_LINK_LIVE_STREAM_CLIENT'
export const GET_LINK_LIVE_STREAM_CLIENT_SUCCESS = 'GET_LINK_LIVE_STREAM_CLIENT_SUCCESS'

export const ADD_NEW_LIVE_STREAM_SUCCESS = 'ADD_NEW_LIVE_STREAM_SUCCESS'
export const DELETE_LIVE_STREAM_FINISH_SUCCESS = 'DELETE_LIVE_STREAM_FINISH_SUCCESS'

export const REGISTER_ROOM_LIVE_STREAM_SUCCESS = 'REGISTER_ROOM_LIVE_STREAM_SUCCESS'

export const UPDATE_ROOM_LIVE_STREAM_SUCCESS = 'UPDATE_ROOM_LIVE_STREAM_SUCCESS'
export const ADD_NEW_COMMENT_LIVE_STREAM_SUCCESS = 'ADD_NEW_COMMENT_LIVE_STREAM_SUCCESS'
